// RegressionHarness.cs
// No Roslyn dependency — uses Unity's CompilationPipeline instead.
// Before applying a fix: snapshot current compile error count via Unity.
// After applying: re-check and compare. Auto-revert if errors increase.

using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using UnityEditor;
using UnityEditor.Compilation;
using Newtonsoft.Json;

namespace SolidAgent
{
    public class RegressionHarness
    {
        private readonly string _baselineDir;

        public RegressionHarness(string projectRoot)
        {
            _baselineDir = Path.Combine(projectRoot, "..", "solid-agent-baselines");
            Directory.CreateDirectory(_baselineDir);
        }

        // ── Step 1: Capture baseline ──────────────────────────────────────────────

        public Task CaptureBaselineAsync(string filePath)
        {
            // Baseline = zero errors assumed on unmodified file.
            // We save the file hash so we can detect if it changed.
            var result = new CompileResult
            {
                ErrorCount  = 0,
                FileHash    = FileHash(filePath)
            };
            string path = Path.Combine(_baselineDir, FileKey(filePath) + ".json");
            File.WriteAllText(path, JsonConvert.SerializeObject(result));
            return Task.CompletedTask;
        }

        // ── Step 2: Apply fix to disk ─────────────────────────────────────────────

        public void ApplyFix(GeneratedFix fix, string filePath)
        {
            if (string.IsNullOrWhiteSpace(fix.FixedCode)) return;

            string backup = filePath + ".solid-backup";
            if (!File.Exists(backup)) File.Copy(filePath, backup);

            File.WriteAllText(filePath, fix.FixedCode);

            // Create stub files for any new classes the fix needs
            string dir = Path.GetDirectoryName(filePath);
            foreach (var newFile in fix.NewFilesNeeded)
            {
                string dest = Path.Combine(dir, newFile);
                if (!File.Exists(dest))
                    File.WriteAllText(dest, $"// {newFile} — generated by SOLID Agent\n");
            }
        }

        public void RevertFix(string filePath)
        {
            string backup = filePath + ".solid-backup";
            if (!File.Exists(backup)) return;
            File.Copy(backup, filePath, overwrite: true);
            File.Delete(backup);
        }

        // ── Step 3: Check after applying ─────────────────────────────────────────
        // Uses Unity's CompilationPipeline to get assembly errors — no Roslyn needed.

        public Task<RegressionReport> CompareAsync(string filePath)
        {
            var report = new RegressionReport { FilePath = filePath };

            // Ask Unity to recompile and collect errors
            var errors = new List<string>();

            // CompilationPipeline.assemblyCompilationFinished fires after recompile
            // For a synchronous check we use the lighter AssemblyBuilder approach,
            // but the simplest Unity-safe method is to check CompilationPipeline
            // for any current errors via the EditorUtility.scriptCompilationFailed flag.

            bool compileFailed = EditorUtility.scriptCompilationFailed;

            report.Tests.Add(new TestCase
            {
                Id             = "unity-compile",
                Description    = "Unity compiles project without errors",
                ExpectedOutput = "no errors",
                ActualOutput   = compileFailed ? "compile errors detected" : "no errors"
            });

            // Also do a basic syntax check — look for unmatched braces in the file
            var syntaxErrors = BasicSyntaxCheck(filePath);
            foreach (var err in syntaxErrors)
            {
                report.Tests.Add(new TestCase
                {
                    Id             = "syntax",
                    Description    = err,
                    ExpectedOutput = "no error",
                    ActualOutput   = "syntax issue"
                });
            }

            return Task.FromResult(report);
        }

        // ── Basic syntax check (no Roslyn) ────────────────────────────────────────
        // Catches obvious issues: unmatched braces, missing semicolons on obvious lines.

        private List<string> BasicSyntaxCheck(string filePath)
        {
            var issues = new List<string>();
            if (!File.Exists(filePath)) return issues;

            string source = File.ReadAllText(filePath);

            // Check brace balance
            int open = 0, close = 0;
            foreach (char c in source) { if (c == '{') open++; else if (c == '}') close++; }
            if (open != close)
                issues.Add($"Unmatched braces — {open} open, {close} close");

            // Check parenthesis balance
            int pOpen = 0, pClose = 0;
            foreach (char c in source) { if (c == '(') pOpen++; else if (c == ')') pClose++; }
            if (pOpen != pClose)
                issues.Add($"Unmatched parentheses — {pOpen} open, {pClose} close");

            return issues;
        }

        // ── Helpers ───────────────────────────────────────────────────────────────

        private string FileKey(string fp)
            => Path.GetFileNameWithoutExtension(fp).Replace(" ", "_");

        private string FileHash(string fp)
        {
            if (!File.Exists(fp)) return "";
            using var md5 = System.Security.Cryptography.MD5.Create();
            using var stream = File.OpenRead(fp);
            var hash = md5.ComputeHash(stream);
            return System.BitConverter.ToString(hash).Replace("-", "");
        }

        private class CompileResult
        {
            public int    ErrorCount { get; set; }
            public string FileHash   { get; set; }
        }
    }
}
